# Generated by Django 4.2.7 on 2024-01-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_student_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_gender', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='enroll.student')),
            ],
        ),
    ]
